name: COVID Box

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: andatoshiki/toshiki-covidbox@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COUNTRY: ${{ secrets.COUNTRY }}
          GIST_ID: ${{ secrets.GIST_ID }}
